//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal_PVI.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PVI_ProyectoFinalEntities1 : DbContext
    {
        public PVI_ProyectoFinalEntities1()
            : base("name=PVI_ProyectoFinalEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<Habitacion> Habitacion { get; set; }
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Reservacion> Reservacion { get; set; }
    
        public virtual int spCancelarReservacion(Nullable<int> idReservacion, Nullable<System.DateTime> fechaModificacion)
        {
            var idReservacionParameter = idReservacion.HasValue ?
                new ObjectParameter("idReservacion", idReservacion) :
                new ObjectParameter("idReservacion", typeof(int));
    
            var fechaModificacionParameter = fechaModificacion.HasValue ?
                new ObjectParameter("fechaModificacion", fechaModificacion) :
                new ObjectParameter("fechaModificacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCancelarReservacion", idReservacionParameter, fechaModificacionParameter);
        }
    
        public virtual ObjectResult<spConsultarAccionesRealizadasPorId_Result> spConsultarAccionesRealizadasPorId(Nullable<int> idReservaciones)
        {
            var idReservacionesParameter = idReservaciones.HasValue ?
                new ObjectParameter("IdReservaciones", idReservaciones) :
                new ObjectParameter("IdReservaciones", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarAccionesRealizadasPorId_Result>("spConsultarAccionesRealizadasPorId", idReservacionesParameter);
        }
    
        public virtual ObjectResult<spConsultarDetalleReservacionPorId_Result> spConsultarDetalleReservacionPorId(Nullable<int> idReservacion)
        {
            var idReservacionParameter = idReservacion.HasValue ?
                new ObjectParameter("IdReservacion", idReservacion) :
                new ObjectParameter("IdReservacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarDetalleReservacionPorId_Result>("spConsultarDetalleReservacionPorId", idReservacionParameter);
        }
    
        public virtual ObjectResult<spConsultarDetalleReservacionPorIdB_Result> spConsultarDetalleReservacionPorIdB(Nullable<int> idReservacion)
        {
            var idReservacionParameter = idReservacion.HasValue ?
                new ObjectParameter("IdReservacion", idReservacion) :
                new ObjectParameter("IdReservacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarDetalleReservacionPorIdB_Result>("spConsultarDetalleReservacionPorIdB", idReservacionParameter);
        }
    
        public virtual ObjectResult<string> spConsultarHabitacionConReservacion(Nullable<int> idHotel, string numeroHabitacion)
        {
            var idHotelParameter = idHotel.HasValue ?
                new ObjectParameter("idHotel", idHotel) :
                new ObjectParameter("idHotel", typeof(int));
    
            var numeroHabitacionParameter = numeroHabitacion != null ?
                new ObjectParameter("numeroHabitacion", numeroHabitacion) :
                new ObjectParameter("numeroHabitacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spConsultarHabitacionConReservacion", idHotelParameter, numeroHabitacionParameter);
        }
    
        public virtual ObjectResult<spConsultarHabitaciones_Result> spConsultarHabitaciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarHabitaciones_Result>("spConsultarHabitaciones");
        }
    
        public virtual ObjectResult<string> spConsultarHabitacionesPorIdHotel(Nullable<int> idHotel, string numeroHabitacion)
        {
            var idHotelParameter = idHotel.HasValue ?
                new ObjectParameter("idHotel", idHotel) :
                new ObjectParameter("idHotel", typeof(int));
    
            var numeroHabitacionParameter = numeroHabitacion != null ?
                new ObjectParameter("numeroHabitacion", numeroHabitacion) :
                new ObjectParameter("numeroHabitacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spConsultarHabitacionesPorIdHotel", idHotelParameter, numeroHabitacionParameter);
        }
    
        public virtual ObjectResult<spConsultarHabitacionPorId_Result> spConsultarHabitacionPorId(Nullable<int> idHabitacion)
        {
            var idHabitacionParameter = idHabitacion.HasValue ?
                new ObjectParameter("idHabitacion", idHabitacion) :
                new ObjectParameter("idHabitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarHabitacionPorId_Result>("spConsultarHabitacionPorId", idHabitacionParameter);
        }
    
        public virtual ObjectResult<string> spConsultarHabitacionSinReservacion(Nullable<int> idHotel, Nullable<int> capacidadMaxima)
        {
            var idHotelParameter = idHotel.HasValue ?
                new ObjectParameter("idHotel", idHotel) :
                new ObjectParameter("idHotel", typeof(int));
    
            var capacidadMaximaParameter = capacidadMaxima.HasValue ?
                new ObjectParameter("capacidadMaxima", capacidadMaxima) :
                new ObjectParameter("capacidadMaxima", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spConsultarHabitacionSinReservacion", idHotelParameter, capacidadMaximaParameter);
        }
    
        public virtual ObjectResult<spConsultarHoteles_Result> spConsultarHoteles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarHoteles_Result>("spConsultarHoteles");
        }
    
        public virtual ObjectResult<spConsultarIdDeHabitacion_Result> spConsultarIdDeHabitacion(string numeroHabitacion)
        {
            var numeroHabitacionParameter = numeroHabitacion != null ?
                new ObjectParameter("numeroHabitacion", numeroHabitacion) :
                new ObjectParameter("numeroHabitacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarIdDeHabitacion_Result>("spConsultarIdDeHabitacion", numeroHabitacionParameter);
        }
    
        public virtual ObjectResult<spConsultarIdReservacion_Result> spConsultarIdReservacion(Nullable<int> idReservacion)
        {
            var idReservacionParameter = idReservacion.HasValue ?
                new ObjectParameter("idReservacion", idReservacion) :
                new ObjectParameter("idReservacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarIdReservacion_Result>("spConsultarIdReservacion", idReservacionParameter);
        }
    
        public virtual ObjectResult<string> spConsultarNumerodeHabitaciones(string numeroHabitacion)
        {
            var numeroHabitacionParameter = numeroHabitacion != null ?
                new ObjectParameter("numeroHabitacion", numeroHabitacion) :
                new ObjectParameter("numeroHabitacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spConsultarNumerodeHabitaciones", numeroHabitacionParameter);
        }
    
        public virtual ObjectResult<spConsultarPersonas_Result> spConsultarPersonas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarPersonas_Result>("spConsultarPersonas");
        }
    
        public virtual ObjectResult<spConsultarPreciosPorIdHotel_Result> spConsultarPreciosPorIdHotel(Nullable<int> idHotel)
        {
            var idHotelParameter = idHotel.HasValue ?
                new ObjectParameter("idHotel", idHotel) :
                new ObjectParameter("idHotel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarPreciosPorIdHotel_Result>("spConsultarPreciosPorIdHotel", idHotelParameter);
        }
    
        public virtual ObjectResult<spConsultarReservaciones_Result> spConsultarReservaciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarReservaciones_Result>("spConsultarReservaciones");
        }
    
        public virtual ObjectResult<spConsultarReservacionesFiltro_Result> spConsultarReservacionesFiltro(Nullable<int> idPersona, Nullable<System.DateTime> fechaEntrada, Nullable<System.DateTime> fechaSalida)
        {
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("IdPersona", idPersona) :
                new ObjectParameter("IdPersona", typeof(int));
    
            var fechaEntradaParameter = fechaEntrada.HasValue ?
                new ObjectParameter("fechaEntrada", fechaEntrada) :
                new ObjectParameter("fechaEntrada", typeof(System.DateTime));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("fechaSalida", fechaSalida) :
                new ObjectParameter("fechaSalida", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarReservacionesFiltro_Result>("spConsultarReservacionesFiltro", idPersonaParameter, fechaEntradaParameter, fechaSalidaParameter);
        }
    
        public virtual ObjectResult<spConsultarReservacionesPorId_Result> spConsultarReservacionesPorId(Nullable<int> idPersona)
        {
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("IdPersona", idPersona) :
                new ObjectParameter("IdPersona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarReservacionesPorId_Result>("spConsultarReservacionesPorId", idPersonaParameter);
        }
    
        public virtual ObjectResult<spConsultarReservacionPorNumeroHabitacion_Result> spConsultarReservacionPorNumeroHabitacion(Nullable<int> idHabitacion)
        {
            var idHabitacionParameter = idHabitacion.HasValue ?
                new ObjectParameter("idHabitacion", idHabitacion) :
                new ObjectParameter("idHabitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarReservacionPorNumeroHabitacion_Result>("spConsultarReservacionPorNumeroHabitacion", idHabitacionParameter);
        }
    
        public virtual ObjectResult<spConsultarUltimaReservacionRealizada_Result> spConsultarUltimaReservacionRealizada()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarUltimaReservacionRealizada_Result>("spConsultarUltimaReservacionRealizada");
        }
    
        public virtual int spCrearHabitacion(Nullable<int> idHotel, string numeroHabitacion, Nullable<int> capacidadMaxima, string descripcion, string estado)
        {
            var idHotelParameter = idHotel.HasValue ?
                new ObjectParameter("idHotel", idHotel) :
                new ObjectParameter("idHotel", typeof(int));
    
            var numeroHabitacionParameter = numeroHabitacion != null ?
                new ObjectParameter("numeroHabitacion", numeroHabitacion) :
                new ObjectParameter("numeroHabitacion", typeof(string));
    
            var capacidadMaximaParameter = capacidadMaxima.HasValue ?
                new ObjectParameter("capacidadMaxima", capacidadMaxima) :
                new ObjectParameter("capacidadMaxima", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCrearHabitacion", idHotelParameter, numeroHabitacionParameter, capacidadMaximaParameter, descripcionParameter, estadoParameter);
        }
    
        public virtual int spCrearRegistroBitacora(Nullable<int> idReservacion, Nullable<int> idPersona, string accionRealizada, Nullable<System.DateTime> fechaDeLaAccion)
        {
            var idReservacionParameter = idReservacion.HasValue ?
                new ObjectParameter("idReservacion", idReservacion) :
                new ObjectParameter("idReservacion", typeof(int));
    
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("idPersona", idPersona) :
                new ObjectParameter("idPersona", typeof(int));
    
            var accionRealizadaParameter = accionRealizada != null ?
                new ObjectParameter("accionRealizada", accionRealizada) :
                new ObjectParameter("accionRealizada", typeof(string));
    
            var fechaDeLaAccionParameter = fechaDeLaAccion.HasValue ?
                new ObjectParameter("fechaDeLaAccion", fechaDeLaAccion) :
                new ObjectParameter("fechaDeLaAccion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCrearRegistroBitacora", idReservacionParameter, idPersonaParameter, accionRealizadaParameter, fechaDeLaAccionParameter);
        }
    
        public virtual int spCrearReservacion(Nullable<int> idPersona, Nullable<int> idHabitacion, Nullable<System.DateTime> fechaEntrada, Nullable<System.DateTime> fechaSalida, Nullable<int> numeroAdultos, Nullable<int> numeroNinhos, Nullable<int> totalDiasReservacion, Nullable<decimal> costoPorCadaAdulto, Nullable<decimal> costoPorCadaNinho, Nullable<decimal> costoTotal, Nullable<System.DateTime> fechaCreacion, string estado)
        {
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("idPersona", idPersona) :
                new ObjectParameter("idPersona", typeof(int));
    
            var idHabitacionParameter = idHabitacion.HasValue ?
                new ObjectParameter("idHabitacion", idHabitacion) :
                new ObjectParameter("idHabitacion", typeof(int));
    
            var fechaEntradaParameter = fechaEntrada.HasValue ?
                new ObjectParameter("fechaEntrada", fechaEntrada) :
                new ObjectParameter("fechaEntrada", typeof(System.DateTime));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("fechaSalida", fechaSalida) :
                new ObjectParameter("fechaSalida", typeof(System.DateTime));
    
            var numeroAdultosParameter = numeroAdultos.HasValue ?
                new ObjectParameter("numeroAdultos", numeroAdultos) :
                new ObjectParameter("numeroAdultos", typeof(int));
    
            var numeroNinhosParameter = numeroNinhos.HasValue ?
                new ObjectParameter("numeroNinhos", numeroNinhos) :
                new ObjectParameter("numeroNinhos", typeof(int));
    
            var totalDiasReservacionParameter = totalDiasReservacion.HasValue ?
                new ObjectParameter("totalDiasReservacion", totalDiasReservacion) :
                new ObjectParameter("totalDiasReservacion", typeof(int));
    
            var costoPorCadaAdultoParameter = costoPorCadaAdulto.HasValue ?
                new ObjectParameter("costoPorCadaAdulto", costoPorCadaAdulto) :
                new ObjectParameter("costoPorCadaAdulto", typeof(decimal));
    
            var costoPorCadaNinhoParameter = costoPorCadaNinho.HasValue ?
                new ObjectParameter("costoPorCadaNinho", costoPorCadaNinho) :
                new ObjectParameter("costoPorCadaNinho", typeof(decimal));
    
            var costoTotalParameter = costoTotal.HasValue ?
                new ObjectParameter("costoTotal", costoTotal) :
                new ObjectParameter("costoTotal", typeof(decimal));
    
            var fechaCreacionParameter = fechaCreacion.HasValue ?
                new ObjectParameter("fechaCreacion", fechaCreacion) :
                new ObjectParameter("fechaCreacion", typeof(System.DateTime));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCrearReservacion", idPersonaParameter, idHabitacionParameter, fechaEntradaParameter, fechaSalidaParameter, numeroAdultosParameter, numeroNinhosParameter, totalDiasReservacionParameter, costoPorCadaAdultoParameter, costoPorCadaNinhoParameter, costoTotalParameter, fechaCreacionParameter, estadoParameter);
        }
    
        public virtual int spEditarHabitacion(Nullable<int> idHabitacion, Nullable<int> idHotel, string numeroHabitacion, Nullable<int> capacidadMaxima, string descripcion, string estado)
        {
            var idHabitacionParameter = idHabitacion.HasValue ?
                new ObjectParameter("idHabitacion", idHabitacion) :
                new ObjectParameter("idHabitacion", typeof(int));
    
            var idHotelParameter = idHotel.HasValue ?
                new ObjectParameter("idHotel", idHotel) :
                new ObjectParameter("idHotel", typeof(int));
    
            var numeroHabitacionParameter = numeroHabitacion != null ?
                new ObjectParameter("numeroHabitacion", numeroHabitacion) :
                new ObjectParameter("numeroHabitacion", typeof(string));
    
            var capacidadMaximaParameter = capacidadMaxima.HasValue ?
                new ObjectParameter("capacidadMaxima", capacidadMaxima) :
                new ObjectParameter("capacidadMaxima", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEditarHabitacion", idHabitacionParameter, idHotelParameter, numeroHabitacionParameter, capacidadMaximaParameter, descripcionParameter, estadoParameter);
        }
    
        public virtual int spEditarReservacion(Nullable<int> idReservacion, Nullable<System.DateTime> fechaEntrada, Nullable<System.DateTime> fechaSalida, Nullable<int> numeroAdultos, Nullable<int> numeroNinhos, Nullable<int> totalDiasReservacion, Nullable<decimal> costoPorCadaAdulto, Nullable<decimal> costoPorCadaNinho, Nullable<decimal> costoTotal, Nullable<System.DateTime> fechaModificacion)
        {
            var idReservacionParameter = idReservacion.HasValue ?
                new ObjectParameter("idReservacion", idReservacion) :
                new ObjectParameter("idReservacion", typeof(int));
    
            var fechaEntradaParameter = fechaEntrada.HasValue ?
                new ObjectParameter("fechaEntrada", fechaEntrada) :
                new ObjectParameter("fechaEntrada", typeof(System.DateTime));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("fechaSalida", fechaSalida) :
                new ObjectParameter("fechaSalida", typeof(System.DateTime));
    
            var numeroAdultosParameter = numeroAdultos.HasValue ?
                new ObjectParameter("numeroAdultos", numeroAdultos) :
                new ObjectParameter("numeroAdultos", typeof(int));
    
            var numeroNinhosParameter = numeroNinhos.HasValue ?
                new ObjectParameter("numeroNinhos", numeroNinhos) :
                new ObjectParameter("numeroNinhos", typeof(int));
    
            var totalDiasReservacionParameter = totalDiasReservacion.HasValue ?
                new ObjectParameter("totalDiasReservacion", totalDiasReservacion) :
                new ObjectParameter("totalDiasReservacion", typeof(int));
    
            var costoPorCadaAdultoParameter = costoPorCadaAdulto.HasValue ?
                new ObjectParameter("costoPorCadaAdulto", costoPorCadaAdulto) :
                new ObjectParameter("costoPorCadaAdulto", typeof(decimal));
    
            var costoPorCadaNinhoParameter = costoPorCadaNinho.HasValue ?
                new ObjectParameter("costoPorCadaNinho", costoPorCadaNinho) :
                new ObjectParameter("costoPorCadaNinho", typeof(decimal));
    
            var costoTotalParameter = costoTotal.HasValue ?
                new ObjectParameter("costoTotal", costoTotal) :
                new ObjectParameter("costoTotal", typeof(decimal));
    
            var fechaModificacionParameter = fechaModificacion.HasValue ?
                new ObjectParameter("fechaModificacion", fechaModificacion) :
                new ObjectParameter("fechaModificacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEditarReservacion", idReservacionParameter, fechaEntradaParameter, fechaSalidaParameter, numeroAdultosParameter, numeroNinhosParameter, totalDiasReservacionParameter, costoPorCadaAdultoParameter, costoPorCadaNinhoParameter, costoTotalParameter, fechaModificacionParameter);
        }
    
        public virtual int spInactivarHabitacion(Nullable<int> idHabitacion)
        {
            var idHabitacionParameter = idHabitacion.HasValue ?
                new ObjectParameter("idHabitacion", idHabitacion) :
                new ObjectParameter("idHabitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInactivarHabitacion", idHabitacionParameter);
        }
    
        public virtual ObjectResult<spLogin_Result> spLogin(string correo, string clave)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spLogin_Result>("spLogin", correoParameter, claveParameter);
        }
    }
}
